name: Character Tags Match

permissions:
  contents: write

on:
#  push:
  workflow_dispatch:
#  schedule:
#    - cron: '30 14 * * *'

jobs:
  tag_match:
    name: Tag Match
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
#      max-parallel: 1
      matrix:
        resource:
          - 'anime_pictures'
          - 'zerochan'
          - 'danbooru'
          - 'safebooru'
          - 'atfbooru'
          - 'sankaku'
          - 'rule34'
          - 'hypnohub'
          - 'xbooru'
          - 'konachan'
          - 'konachan_net'
          - 'yande'
          - 'lolibooru'
          - 'gelbooru'
#          - 'pixiv'
          - 'wallhaven'
        game:
#          - 'bluearchive'
#          - 'arknights'
#          - 'fgo'
#          - 'azurlane'
#          - 'girlsfrontline'
#          - 'genshin'
#          - 'neuralcloud'
#          - 'pathtonowhere'
#          - 'nikke'
#          - 'starrail'
#          - 'bangdream'
#          - 'demonslayer'
#          - 'eromangasensei'
#          - 'lovelive'
#          - 'lovelivesunshine'
#          - 'mahoushoujomadokamagica'
#          - 'naruto'
#          - 'pokemon'
#          - 'rezero'
#          - 'swordartonline'
#          - 'touhou'
#          - 'violetevergarden'
#          - 'vocaloid'
#          - 'yugioh'
#          - 'spyxfamily'
#          - 'isitwrongtotrytopickupgirlsinadungeon'
#          - 'toarumajutsunoindex'
#          - 'konosuba'
#          - 'kantaicollection'
#          - 'honkai3'
          - 'touhou'
        os:
          - 'ubuntu-latest'
        python-version:
          - '3.8'

    steps:
      - name: Get system version for Linux
        if: ${{ contains(matrix.os, 'ubuntu') }}
        shell: bash
        run: |
          echo "OS_NAME=Linux" >> $GITHUB_ENV
          echo "IS_WIN=" >> $GITHUB_ENV
          echo "IS_MAC=" >> $GITHUB_ENV
      - name: Set environment for Cpython
        if: ${{ !contains(matrix.python-version, 'pypy') }}
        shell: bash
        run: |
          echo "IS_PYPY=" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
          submodules: 'recursive'
      - name: Set up system dependencies on Linux
        if: ${{ env.OS_NAME == 'Linux' }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y tree cloc wget curl make zip
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install -r requirements-crawl.txt
      - name: Test the basic environment
        shell: bash
        run: |
          python -V
          pip --version
          pip list
          tree .
      - name: Run Game Crawler
        uses: nick-fields/retry@v2
        env:
          CI: 'true'
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        with:
          shell: bash
          timeout_minutes: 360
          max_attempts: 5
          retry_on: any
          command: |
            python -m zoo.resources.${{ matrix.resource }} chtags -g ${{ matrix.game }} --max_time '5.5 hours'

  tag_match_1:
    name: Tag Match
    runs-on: ${{ matrix.os }}
    needs:
      - tag_match
    strategy:
      fail-fast: false
      matrix:
        resource:
          - 'anime_pictures'
          - 'zerochan'
          - 'danbooru'
          - 'safebooru'
          - 'atfbooru'
          - 'sankaku'
          - 'rule34'
          - 'hypnohub'
          - 'xbooru'
          - 'konachan'
          - 'konachan_net'
          - 'yande'
          - 'lolibooru'
          - 'gelbooru'
#          - 'pixiv'
          - 'wallhaven'
        game:
#          - 'kantaicollection'
#          - 'honkai3'
          - 'touhou'
        os:
          - 'ubuntu-latest'
        python-version:
          - '3.8'

    steps:
      - name: Get system version for Linux
        if: ${{ contains(matrix.os, 'ubuntu') }}
        shell: bash
        run: |
          echo "OS_NAME=Linux" >> $GITHUB_ENV
          echo "IS_WIN=" >> $GITHUB_ENV
          echo "IS_MAC=" >> $GITHUB_ENV
      - name: Set environment for Cpython
        if: ${{ !contains(matrix.python-version, 'pypy') }}
        shell: bash
        run: |
          echo "IS_PYPY=" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
          submodules: 'recursive'
      - name: Set up system dependencies on Linux
        if: ${{ env.OS_NAME == 'Linux' }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y tree cloc wget curl make zip
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install -r requirements-crawl.txt
      - name: Test the basic environment
        shell: bash
        run: |
          python -V
          pip --version
          pip list
          tree .
      - name: Run Game Crawler
        uses: nick-fields/retry@v2
        env:
          CI: 'true'
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        with:
          shell: bash
          timeout_minutes: 360
          max_attempts: 5
          retry_on: any
          command: |
            python -m zoo.resources.${{ matrix.resource }} chtags -g ${{ matrix.game }} --max_time '5.5 hours'

  tag_match_2:
    name: Tag Match
    runs-on: ${{ matrix.os }}
    needs:
      - tag_match_1
    strategy:
      fail-fast: false
      matrix:
        resource:
          - 'anime_pictures'
          - 'zerochan'
          - 'danbooru'
          - 'safebooru'
          - 'atfbooru'
          - 'sankaku'
          - 'rule34'
          - 'hypnohub'
          - 'xbooru'
          - 'konachan'
          - 'konachan_net'
          - 'yande'
          - 'lolibooru'
          - 'gelbooru'
#          - 'pixiv'
          - 'wallhaven'
        game:
#          - 'kantaicollection'
#          - 'honkai3'
          - 'touhou'
        os:
          - 'ubuntu-latest'
        python-version:
          - '3.8'

    steps:
      - name: Get system version for Linux
        if: ${{ contains(matrix.os, 'ubuntu') }}
        shell: bash
        run: |
          echo "OS_NAME=Linux" >> $GITHUB_ENV
          echo "IS_WIN=" >> $GITHUB_ENV
          echo "IS_MAC=" >> $GITHUB_ENV
      - name: Set environment for Cpython
        if: ${{ !contains(matrix.python-version, 'pypy') }}
        shell: bash
        run: |
          echo "IS_PYPY=" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
          submodules: 'recursive'
      - name: Set up system dependencies on Linux
        if: ${{ env.OS_NAME == 'Linux' }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y tree cloc wget curl make zip
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install -r requirements-crawl.txt
      - name: Test the basic environment
        shell: bash
        run: |
          python -V
          pip --version
          pip list
          tree .
      - name: Run Game Crawler
        uses: nick-fields/retry@v2
        env:
          CI: 'true'
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        with:
          shell: bash
          timeout_minutes: 360
          max_attempts: 5
          retry_on: any
          command: |
            python -m zoo.resources.${{ matrix.resource }} chtags -g ${{ matrix.game }} --max_time '5.5 hours'




#            python -m zoo.resources.${{ matrix.resource }} chtags_export -g ${{ matrix.game }}
#            zip -r ${{ matrix.resource }}_${{ matrix.game }}.zip ${{ matrix.game }}
#      - name: Upload the character databases
#        uses: actions/upload-artifact@v3
#        with:
#          name: character-database
#          path: ${{ matrix.resource }}_${{ matrix.game }}.zip
#
#  data_upload:
#    name: Data Upload
#    runs-on: ${{ matrix.os }}
#    needs:
#      - tag_match
#    strategy:
#      fail-fast: false
#      matrix:
#        os:
#          - 'ubuntu-latest'
#        python-version:
#          - '3.8'
#
#    steps:
#      - name: Prepare the repository
#        shell: bash
#        run: |
#          sudo apt-get install -y tree
#          git clone https://huggingface.co/datasets/deepghs/game_characters
#          ls -al game_characters
#      - name: Download from artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: character-database
#          path: game_characters
#      - name: See what is in this path
#        shell: bash
#        run: |
#          cd game_characters
#          for zfile in *.zip; do unzip -o $zfile; done
#          rm -rf *.zip
#          tree .
#      - name: Push models to hugging face repository
#        env:
#          HF_TOKEN: ${{ secrets.HF_TOKEN }}
#        run: |
#          cd game_characters
#          git config user.name 'narugo1992'
#          git config user.email 'narugo992@gmail.com'
#          git add -A
#          git diff-index --quiet HEAD || git commit -a -m "dev(narugo): auto sync $(date -R)"
#          git push https://narugo:$HF_TOKEN@huggingface.co/datasets/deepghs/game_characters main
